### ISSUE TITLE
Incorrect opening time indicated in Readme

### ISSUE THREAD

**Issue by trulyspinach** [ZijunH/Roche_Biochemical_Pathway_generator#1]
"At least 1 hour of uninterrupted PC time (tested on overclocked i5-7600k)"

However, 1 hour is not required when opening with optimal image viewer software. The benchmarks time without a specified software using is pointless since different software is likely to result in a very different opening time.

I suggest to add the software used for benchmark in readme.

**Comment by ZijunHui** [comment]
That is for stitching the image alone. Opening speed is dependent on RAM size and speed.
